#!/usr/bin/env php
<?php

$dir = __DIR__.'/../../../view';

if (! file_exists($dir))  mkdir($dir, 0777, true);

if(file_exists($dir.'/flash.php'))
{
    echo 'Flash message view already exists.';
} else {
    copy(__DIR__.'/view/flash.php', $dir.'/Flash_Message.php');

    echo 'Flash message view has been published successfully.';
}
